name: CI

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.5.2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm tsc
      - run: pnpm lint

  e2e:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.5.2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm cypress-install
      - run: pnpm e2e:headless

  units:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.5.2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
